# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: release-builds

on:
  release:
    types: 
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Build with Gradle
      run: gradle build
    - name: Publish to GitHub Packages
      uses: AButler/upload-release-assets@v2.0
      with:
          files: 'build/libs/*;LICENSE'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
